apiVersion: skaffold/v4beta9
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: test-file-sync
    jib:
      type: gradle
      args: 
      - -Psync
      - -Djib.dockerClient.executable=/usr/bin/podman
      fromImage: gcr.io/distroless/java:debug
    sync:
      auto: true

portForward:
- resourceType: pod
  resourceName: test-file-sync
  port: 8080
